version: '3.9'
services:
  countrycurrencyapi:
    build: .
    container_name: countrycurrencyapi
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
